/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Gazebo;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class ContactsState : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/ContactsState";

        public Header header;
        //  stamp
        public ContactState[] states;
        //  array of geom pairs in contact

        public ContactsState()
        {
            this.header = new Header();
            this.states = new ContactState[0];
        }

        public ContactsState(Header header, ContactState[] states)
        {
            this.header = header;
            this.states = states;
        }
    }
}
