/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class LinkState : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/LinkState";

        //  @todo: FIXME: sets pose and twist of a link.  All children link poses/twists of the URDF tree are not updated accordingly, but should be.
        public string link_name;
        //  link name, link_names are in gazebo scoped name notation, [model_name::body_name]
        public Pose pose;
        //  desired pose in reference frame
        public Twist twist;
        //  desired twist in reference frame
        public string reference_frame;
        //  set pose/twist relative to the frame of this link/body
        //  leave empty or "world" or "map" defaults to world-frame

        public LinkState()
        {
            this.link_name = "";
            this.pose = new Pose();
            this.twist = new Twist();
            this.reference_frame = "";
        }

        public LinkState(string link_name, Pose pose, Twist twist, string reference_frame)
        {
            this.link_name = link_name;
            this.pose = pose;
            this.twist = twist;
            this.reference_frame = reference_frame;
        }
    }
}
