/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class ODEJointProperties : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/ODEJointProperties";

        //  access to low level joint properties, change these at your own risk
        public double[] damping;
        //  joint damping
        public double[] hiStop;
        //  joint limit
        public double[] loStop;
        //  joint limit
        public double[] erp;
        //  set joint erp
        public double[] cfm;
        //  set joint cfm
        public double[] stop_erp;
        //  set joint erp for joint limit "contact" joint
        public double[] stop_cfm;
        //  set joint cfm for joint limit "contact" joint
        public double[] fudge_factor;
        //  joint fudge_factor applied at limits, see ODE manual for info.
        public double[] fmax;
        //  ode joint param fmax
        public double[] vel;
        //  ode joint param vel

        public ODEJointProperties()
        {
            this.damping = new double[0];
            this.hiStop = new double[0];
            this.loStop = new double[0];
            this.erp = new double[0];
            this.cfm = new double[0];
            this.stop_erp = new double[0];
            this.stop_cfm = new double[0];
            this.fudge_factor = new double[0];
            this.fmax = new double[0];
            this.vel = new double[0];
        }

        public ODEJointProperties(double[] damping, double[] hiStop, double[] loStop, double[] erp, double[] cfm, double[] stop_erp, double[] stop_cfm, double[] fudge_factor, double[] fmax, double[] vel)
        {
            this.damping = damping;
            this.hiStop = hiStop;
            this.loStop = loStop;
            this.erp = erp;
            this.cfm = cfm;
            this.stop_erp = stop_erp;
            this.stop_cfm = stop_cfm;
            this.fudge_factor = fudge_factor;
            this.fmax = fmax;
            this.vel = vel;
        }
    }
}
