/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class ApplyJointEffortRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/ApplyJointEffort";

        //  set urdf joint effort
        public string joint_name;
        //  joint to apply wrench (linear force and torque)
        public double effort;
        //  effort to apply
        public Time start_time;
        //  optional wrench application start time (seconds)
        //  if start_time < current time, start as soon as possible
        public Duration duration;
        //  optional duration of wrench application time (seconds)
        //  if duration < 0, apply wrench continuously without end
        //  if duration = 0, do nothing
        //  if duration < step size, assume step size and
        //                display warning in status_message

        public ApplyJointEffortRequest()
        {
            this.joint_name = "";
            this.effort = 0.0;
            this.start_time = new Time();
            this.duration = new Duration();
        }

        public ApplyJointEffortRequest(string joint_name, double effort, Time start_time, Duration duration)
        {
            this.joint_name = joint_name;
            this.effort = effort;
            this.start_time = start_time;
            this.duration = duration;
        }
    }
}
