/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class GetLinkPropertiesRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/GetLinkProperties";

        public string link_name;
        //  name of link
        //  link names are prefixed by model name, e.g. pr2::base_link

        public GetLinkPropertiesRequest()
        {
            this.link_name = "";
        }

        public GetLinkPropertiesRequest(string link_name)
        {
            this.link_name = link_name;
        }
    }
}
