/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class GetLinkPropertiesResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/GetLinkProperties";

        public Pose com;
        //  center of mass location in link frame
        //  and orientation of the moment of inertias
        //  relative to the link frame
        public bool gravity_mode;
        //  set gravity mode on/off
        public double mass;
        //  linear mass of link
        public double ixx;
        //  moment of inertia
        public double ixy;
        //  moment of inertia
        public double ixz;
        //  moment of inertia
        public double iyy;
        //  moment of inertia
        public double iyz;
        //  moment of inertia
        public double izz;
        //  moment of inertia
        public bool success;
        //  return true if get info is successful
        public string status_message;
        //  comments if available

        public GetLinkPropertiesResponse()
        {
            this.com = new Pose();
            this.gravity_mode = false;
            this.mass = 0.0;
            this.ixx = 0.0;
            this.ixy = 0.0;
            this.ixz = 0.0;
            this.iyy = 0.0;
            this.iyz = 0.0;
            this.izz = 0.0;
            this.success = false;
            this.status_message = "";
        }

        public GetLinkPropertiesResponse(Pose com, bool gravity_mode, double mass, double ixx, double ixy, double ixz, double iyy, double iyz, double izz, bool success, string status_message)
        {
            this.com = com;
            this.gravity_mode = gravity_mode;
            this.mass = mass;
            this.ixx = ixx;
            this.ixy = ixy;
            this.ixz = ixz;
            this.iyy = iyy;
            this.iyz = iyz;
            this.izz = izz;
            this.success = success;
            this.status_message = status_message;
        }
    }
}
