/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Gazebo;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class SetJointPropertiesRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/SetJointProperties";

        public string joint_name;
        //  name of joint
        public ODEJointProperties ode_joint_config;
        //  access to ODE joint dynamics properties

        public SetJointPropertiesRequest()
        {
            this.joint_name = "";
            this.ode_joint_config = new ODEJointProperties();
        }

        public SetJointPropertiesRequest(string joint_name, ODEJointProperties ode_joint_config)
        {
            this.joint_name = joint_name;
            this.ode_joint_config = ode_joint_config;
        }
    }
}
