/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Trajectory;
using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class SetJointTrajectoryRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/SetJointTrajectory";

        public string model_name;
        public JointTrajectory joint_trajectory;
        public Pose model_pose;
        public bool set_model_pose;
        public bool disable_physics_updates;
        //  defaults to false

        public SetJointTrajectoryRequest()
        {
            this.model_name = "";
            this.joint_trajectory = new JointTrajectory();
            this.model_pose = new Pose();
            this.set_model_pose = false;
            this.disable_physics_updates = false;
        }

        public SetJointTrajectoryRequest(string model_name, JointTrajectory joint_trajectory, Pose model_pose, bool set_model_pose, bool disable_physics_updates)
        {
            this.model_name = model_name;
            this.joint_trajectory = joint_trajectory;
            this.model_pose = model_pose;
            this.set_model_pose = set_model_pose;
            this.disable_physics_updates = disable_physics_updates;
        }
    }
}
