/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class SetLightPropertiesRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/SetLightProperties";

        public string light_name;
        //  name of Gazebo Light
        public ColorRGBA diffuse;
        //  diffuse color as red, green, blue, alpha
        public double attenuation_constant;
        public double attenuation_linear;
        public double attenuation_quadratic;

        public SetLightPropertiesRequest()
        {
            this.light_name = "";
            this.diffuse = new ColorRGBA();
            this.attenuation_constant = 0.0;
            this.attenuation_linear = 0.0;
            this.attenuation_quadratic = 0.0;
        }

        public SetLightPropertiesRequest(string light_name, ColorRGBA diffuse, double attenuation_constant, double attenuation_linear, double attenuation_quadratic)
        {
            this.light_name = light_name;
            this.diffuse = diffuse;
            this.attenuation_constant = attenuation_constant;
            this.attenuation_linear = attenuation_linear;
            this.attenuation_quadratic = attenuation_quadratic;
        }
    }
}
