/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Gazebo;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class SetModelStateRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/SetModelState";

        public ModelState model_state;

        public SetModelStateRequest()
        {
            this.model_state = new ModelState();
        }

        public SetModelStateRequest(ModelState model_state)
        {
            this.model_state = model_state;
        }
    }
}
