/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class Block_rotation : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/Block_rotation";

        public byte min_dist_l;
        // minimum distance from left distance sensor
        public byte min_dist_r;
        // minimum distance from right distance sensor
        public byte max_dist_l;
        // maximum distance from left distance sensor
        public byte max_dist_r;
        // maximum distance from right distance sensor
        public float rotation;
        // rotation of block in degrees
        public bool new_measurement;
        // flag to identify new measurement

        public Block_rotation()
        {
            this.min_dist_l = 0;
            this.min_dist_r = 0;
            this.max_dist_l = 0;
            this.max_dist_r = 0;
            this.rotation = 0.0f;
            this.new_measurement = false;
        }

        public Block_rotation(byte min_dist_l, byte min_dist_r, byte max_dist_l, byte max_dist_r, float rotation, bool new_measurement)
        {
            this.min_dist_l = min_dist_l;
            this.min_dist_r = min_dist_r;
            this.max_dist_l = max_dist_l;
            this.max_dist_r = max_dist_r;
            this.rotation = rotation;
            this.new_measurement = new_measurement;
        }
    }
}
