/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class ModelState : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/ModelState";

        //  Set Gazebo Model pose and twist
        public string model_name;
        //  model to set state (pose and twist)
        public Pose pose;
        //  desired pose in reference frame
        public Twist twist;
        //  desired twist in reference frame
        public string reference_frame;
        //  set pose/twist relative to the frame of this entity (Body/Model)
        //  leave empty or "world" or "map" defaults to world-frame

        public ModelState()
        {
            this.model_name = "";
            this.pose = new Pose();
            this.twist = new Twist();
            this.reference_frame = "";
        }

        public ModelState(string model_name, Pose pose, Twist twist, string reference_frame)
        {
            this.model_name = model_name;
            this.pose = pose;
            this.twist = twist;
            this.reference_frame = reference_frame;
        }
    }
}
