/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class ODEPhysics : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/ODEPhysics";

        public bool auto_disable_bodies;
        //  enable auto disabling of bodies, default false
        public uint sor_pgs_precon_iters;
        //  preconditioning inner iterations when uisng projected Gauss Seidel
        public uint sor_pgs_iters;
        //  inner iterations when uisng projected Gauss Seidel
        public double sor_pgs_w;
        //  relaxation parameter when using projected Gauss Seidel, 1 = no relaxation
        public double sor_pgs_rms_error_tol;
        //  rms error tolerance before stopping inner iterations
        public double contact_surface_layer;
        //  contact "dead-band" width
        public double contact_max_correcting_vel;
        //  contact maximum correction velocity
        public double cfm;
        //  global constraint force mixing
        public double erp;
        //  global error reduction parameter
        public uint max_contacts;
        //  maximum contact joints between two geoms

        public ODEPhysics()
        {
            this.auto_disable_bodies = false;
            this.sor_pgs_precon_iters = 0;
            this.sor_pgs_iters = 50;
            this.sor_pgs_w = 1.3;
            this.sor_pgs_rms_error_tol = 0.0;
            this.contact_surface_layer = 0.001;
            this.contact_max_correcting_vel = 100.0;
            this.cfm = 0.0;
            this.erp = 0.2;
            this.max_contacts = 20;
        }

        public ODEPhysics(bool auto_disable_bodies, uint sor_pgs_precon_iters, uint sor_pgs_iters, double sor_pgs_w, double sor_pgs_rms_error_tol, double contact_surface_layer, double contact_max_correcting_vel, double cfm, double erp, uint max_contacts)
        {
            this.auto_disable_bodies = auto_disable_bodies;
            this.sor_pgs_precon_iters = sor_pgs_precon_iters;
            this.sor_pgs_iters = sor_pgs_iters;
            this.sor_pgs_w = sor_pgs_w;
            this.sor_pgs_rms_error_tol = sor_pgs_rms_error_tol;
            this.contact_surface_layer = contact_surface_layer;
            this.contact_max_correcting_vel = contact_max_correcting_vel;
            this.cfm = cfm;
            this.erp = erp;
            this.max_contacts = max_contacts;
        }
    }
}
