/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Arduino
{
    public class rfiduidResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "arduino_msgs/Rfiduid";

        public byte b0;
        //  1st byte of UID
        public byte b1;
        //  2nd byte of UID
        public byte b2;
        //  3rd byte of UID
        public byte b3;
        //  4th byte of UID

        public rfiduidResponse()
        {
            this.b0 = 0;
            this.b1 = 0;
            this.b2 = 0;
            this.b3 = 0;
        }

        public rfiduidResponse(byte b0, byte b1, byte b2, byte b3)
        {
            this.b0 = b0;
            this.b1 = b1;
            this.b2 = b2;
            this.b3 = b3;
        }
    }
}
