/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Arduino
{
    public class SetConveyorbeltSpeedRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "arduino_msgs/SetConveyorbeltSpeed";

        public sbyte speed;
        //  relative speed in % ranging from -100 to 100

        public SetConveyorbeltSpeedRequest()
        {
            this.speed = 0;
        }

        public SetConveyorbeltSpeedRequest(sbyte speed)
        {
            this.speed = speed;
        }
    }
}
