/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class AddDetectedObjectRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/AddDetectedObject";

        public DetectedObject obj;
        public string frame_id;
        public Time timestamp;

        public AddDetectedObjectRequest()
        {
            this.obj = new DetectedObject();
            this.frame_id = "";
            this.timestamp = new Time();
        }

        public AddDetectedObjectRequest(DetectedObject obj, string frame_id, Time timestamp)
        {
            this.obj = obj;
            this.frame_id = frame_id;
            this.timestamp = timestamp;
        }
    }
}
