/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class AddDetectedObjectResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/AddDetectedObject";

        public bool success;

        public AddDetectedObjectResponse()
        {
            this.success = false;
        }

        public AddDetectedObjectResponse(bool success)
        {
            this.success = success;
        }
    }
}
