/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class AddFrameRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/AddFrame";

        public string name;
        public double x;
        public double y;
        public double z;
        public bool useXYZ;
        public double roll;
        public double pitch;
        public double yaw;
        public bool useRotation;

        public AddFrameRequest()
        {
            this.name = "";
            this.x = 0.0;
            this.y = 0.0;
            this.z = 0.0;
            this.useXYZ = false;
            this.roll = 0.0;
            this.pitch = 0.0;
            this.yaw = 0.0;
            this.useRotation = false;
        }

        public AddFrameRequest(string name, double x, double y, double z, bool useXYZ, double roll, double pitch, double yaw, bool useRotation)
        {
            this.name = name;
            this.x = x;
            this.y = y;
            this.z = z;
            this.useXYZ = useXYZ;
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
            this.useRotation = useRotation;
        }
    }
}
