/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class GetDetectedObjectResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/GetDetectedObject";

        public bool success;
        public string frame_id;
        public Time timestamp;
        public DetectedObject obj;

        public GetDetectedObjectResponse()
        {
            this.success = false;
            this.frame_id = "";
            this.timestamp = new Time();
            this.obj = new DetectedObject();
        }

        public GetDetectedObjectResponse(bool success, string frame_id, Time timestamp, DetectedObject obj)
        {
            this.success = success;
            this.frame_id = frame_id;
            this.timestamp = timestamp;
            this.obj = obj;
        }
    }
}
