/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class SetFrameRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/SetFrame";

        public string name;
        public Transform t;

        public SetFrameRequest()
        {
            this.name = "";
            this.t = new Transform();
        }

        public SetFrameRequest(string name, Transform t)
        {
            this.name = name;
            this.t = t;
        }
    }
}
