/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Sensor;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class SetPointcloudRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/SetPointcloud";

        public PointCloud2 cloud;

        public SetPointcloudRequest()
        {
            this.cloud = new PointCloud2();
        }

        public SetPointcloudRequest(PointCloud2 cloud)
        {
            this.cloud = cloud;
        }
    }
}
