/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Arduino
{
    public class Distance : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "arduino_msgs/Distance";

        public byte dist;
        //  distance of detected object from sensor in mm
        public byte status;
        //  status of sensor

        public Distance()
        {
            this.dist = 0;
            this.status = 0;
        }

        public Distance(byte dist, byte status)
        {
            this.dist = dist;
            this.status = status;
        }
    }
}
