/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Arduino
{
    public class Get_velocity : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "arduino_msgs/Get_velocity";

        public sbyte velocity;
        //  velocity of the conveyorbelt in percent

        public Get_velocity()
        {
            this.velocity = 0;
        }

        public Get_velocity(sbyte velocity)
        {
            this.velocity = velocity;
        }
    }
}
