/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class GetLightPropertiesRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/GetLightProperties";

        public string light_name;
        //  name of Gazebo Light

        public GetLightPropertiesRequest()
        {
            this.light_name = "";
        }

        public GetLightPropertiesRequest(string light_name)
        {
            this.light_name = light_name;
        }
    }
}
