/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Gazebo;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class GetLinkStateResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/GetLinkState";

        public LinkState link_state;
        public bool success;
        //  return true if get info is successful
        public string status_message;
        //  comments if available

        public GetLinkStateResponse()
        {
            this.link_state = new LinkState();
            this.success = false;
            this.status_message = "";
        }

        public GetLinkStateResponse(LinkState link_state, bool success, string status_message)
        {
            this.link_state = link_state;
            this.success = success;
            this.status_message = status_message;
        }
    }
}
