/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Gazebo;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class SetLinkStateRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/SetLinkState";

        public LinkState link_state;

        public SetLinkStateRequest()
        {
            this.link_state = new LinkState();
        }

        public SetLinkStateRequest(LinkState link_state)
        {
            this.link_state = link_state;
        }
    }
}
