/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Gazebo
{
    public class SetModelConfigurationRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "gazebo_msgs/SetModelConfiguration";

        //  Set joint positions for a model
        public string model_name;
        //  model to set state
        public string urdf_param_name;
        //  UNUSED
        public string[] joint_names;
        //  list of joints to set positions.  if joint is not listed here, preserve current position.
        public double[] joint_positions;
        //  set to this position.

        public SetModelConfigurationRequest()
        {
            this.model_name = "";
            this.urdf_param_name = "";
            this.joint_names = new string[0];
            this.joint_positions = new double[0];
        }

        public SetModelConfigurationRequest(string model_name, string urdf_param_name, string[] joint_names, double[] joint_positions)
        {
            this.model_name = model_name;
            this.urdf_param_name = urdf_param_name;
            this.joint_names = joint_names;
            this.joint_positions = joint_positions;
        }
    }
}
