uint8 min_dist_l            #minimum distance from left distance sensor
uint8 min_dist_r            #minimum distance from right distance sensor
uint8 max_dist_l            #maximum distance from left distance sensor
uint8 max_dist_r            #maximum distance from right distance sensor
float32 rotation            #rotation of block in degrees
bool new_measurement        #flag to identify new measurement