/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class DetectedGrid : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/DetectedGrid";

        public Point basePoint;
        public Vector3 lineVector;
        public Time timestamp;

        public DetectedGrid()
        {
            this.basePoint = new Point();
            this.lineVector = new Vector3();
            this.timestamp = new Time();
        }

        public DetectedGrid(Point basePoint, Vector3 lineVector, Time timestamp)
        {
            this.basePoint = basePoint;
            this.lineVector = lineVector;
            this.timestamp = timestamp;
        }
    }
}
