/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class DetectedDominos : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/DetectedDominos";

        public DetectedDomino[] dominos;
        public string frame_id;

        public DetectedDominos()
        {
            this.dominos = new DetectedDomino[0];
            this.frame_id = "";
        }

        public DetectedDominos(DetectedDomino[] dominos, string frame_id)
        {
            this.dominos = dominos;
            this.frame_id = frame_id;
        }
    }
}
