/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class DetectedDomino : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/DetectedDomino";

        public Point graspPoint;
        public Quaternion rotation;
        public byte[] colorFirst;
        public byte[] colorSecond;
        public Time timestamp;

        public DetectedDomino()
        {
            this.graspPoint = new Point();
            this.rotation = new Quaternion();
            this.colorFirst = new byte[0];
            this.colorSecond = new byte[0];
            this.timestamp = new Time();
        }

        public DetectedDomino(Point graspPoint, Quaternion rotation, byte[] colorFirst, byte[] colorSecond, Time timestamp)
        {
            this.graspPoint = graspPoint;
            this.rotation = rotation;
            this.colorFirst = colorFirst;
            this.colorSecond = colorSecond;
            this.timestamp = timestamp;
        }
    }
}
