/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class DetectedObjects : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/DetectedObjects";

        public DetectedObject[] objects;
        public string frame_id;

        public DetectedObjects()
        {
            this.objects = new DetectedObject[0];
            this.frame_id = "";
        }

        public DetectedObjects(DetectedObject[] objects, string frame_id)
        {
            this.objects = objects;
            this.frame_id = frame_id;
        }
    }
}
