/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Detection
{
    public class DetectedObject : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "detection_msgs/DetectedObject";

        public Point graspPoint;
        public Point startPoint;
        public Point endPoint;
        public Quaternion rotation;
        public float[] color;
        public string type;
        public double probability;
        public Time timestamp;

        public DetectedObject()
        {
            this.graspPoint = new Point();
            this.startPoint = new Point();
            this.endPoint = new Point();
            this.rotation = new Quaternion();
            this.color = new float[0];
            this.type = "";
            this.probability = 0.0;
            this.timestamp = new Time();
        }

        public DetectedObject(Point graspPoint, Point startPoint, Point endPoint, Quaternion rotation, float[] color, string type, double probability, Time timestamp)
        {
            this.graspPoint = graspPoint;
            this.startPoint = startPoint;
            this.endPoint = endPoint;
            this.rotation = rotation;
            this.color = color;
            this.type = type;
            this.probability = probability;
            this.timestamp = timestamp;
        }
    }
}
