Dobot_Rail:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  joint_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - Dobot_Rail_rail_joint
      - Dobot_Rail_base_joint
      - Dobot_Rail_shoulder_joint
      - Dobot_Rail_elbow_joint
      - Dobot_Rail_tool_joint
      
    gains:
      Dobot_Rail_rail_joint: {p: 5000,  d: 0.0, i: 0.0, i_clamp: 1}
      Dobot_Rail_base_joint: {p: 500,  d: 1.0, i: 1.0, i_clamp: 1}
      Dobot_Rail_shoulder_joint: {p: 500,  d: 1.0, i: 1.0, i_clamp: 1}
      Dobot_Rail_elbow_joint: {p: 500,  d: 1.0, i: 1.0, i_clamp: 1}
      Dobot_Rail_tool_joint: {p: 50.0,  d: 0.0001, i: 0.001, i_clamp: 0.05}