/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetAlarmsStateResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetAlarmsState";

        public int result;
        public byte[] alarmsState;

        public GetAlarmsStateResponse()
        {
            this.result = 0;
            this.alarmsState = new byte[0];
        }

        public GetAlarmsStateResponse(int result, byte[] alarmsState)
        {
            this.result = result;
            this.alarmsState = alarmsState;
        }
    }
}
