/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetARCParamsResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetARCParams";

        public int result;
        public float xyzVelocity;
        public float rVelocity;
        public float xyzAcceleration;
        public float rAcceleration;

        public GetARCParamsResponse()
        {
            this.result = 0;
            this.xyzVelocity = 0.0f;
            this.rVelocity = 0.0f;
            this.xyzAcceleration = 0.0f;
            this.rAcceleration = 0.0f;
        }

        public GetARCParamsResponse(int result, float xyzVelocity, float rVelocity, float xyzAcceleration, float rAcceleration)
        {
            this.result = result;
            this.xyzVelocity = xyzVelocity;
            this.rVelocity = rVelocity;
            this.xyzAcceleration = xyzAcceleration;
            this.rAcceleration = rAcceleration;
        }
    }
}
