/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetCPCmdResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetCPCmd";

        public int result;
        public byte cpMode;
        public float x;
        public float y;
        public float z;
        public float velocity;

        public GetCPCmdResponse()
        {
            this.result = 0;
            this.cpMode = 0;
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.velocity = 0.0f;
        }

        public GetCPCmdResponse(int result, byte cpMode, float x, float y, float z, float velocity)
        {
            this.result = result;
            this.cpMode = cpMode;
            this.x = x;
            this.y = y;
            this.z = z;
            this.velocity = velocity;
        }
    }
}
