/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetColorSensorResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetColorSensor";

        public int result;
        public byte r;
        public byte g;
        public byte b;

        public GetColorSensorResponse()
        {
            this.result = 0;
            this.r = 0;
            this.g = 0;
            this.b = 0;
        }

        public GetColorSensorResponse(int result, byte r, byte g, byte b)
        {
            this.result = result;
            this.r = r;
            this.g = g;
            this.b = b;
        }
    }
}
