/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetDeviceSNResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetDeviceSN";

        public int result;
        public String deviceSN;

        public GetDeviceSNResponse()
        {
            this.result = 0;
            this.deviceSN = new String();
        }

        public GetDeviceSNResponse(int result, String deviceSN)
        {
            this.result = result;
            this.deviceSN = deviceSN;
        }
    }
}
