/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetDeviceVersionResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetDeviceVersion";

        public int result;
        public byte majorVersion;
        public byte minorVersion;
        public byte revision;

        public GetDeviceVersionResponse()
        {
            this.result = 0;
            this.majorVersion = 0;
            this.minorVersion = 0;
            this.revision = 0;
        }

        public GetDeviceVersionResponse(int result, byte majorVersion, byte minorVersion, byte revision)
        {
            this.result = result;
            this.majorVersion = majorVersion;
            this.minorVersion = minorVersion;
            this.revision = revision;
        }
    }
}
