/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetEndEffectorParamsResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetEndEffectorParams";

        public int result;
        public float xBias;
        public float yBias;
        public float zBias;

        public GetEndEffectorParamsResponse()
        {
            this.result = 0;
            this.xBias = 0.0f;
            this.yBias = 0.0f;
            this.zBias = 0.0f;
        }

        public GetEndEffectorParamsResponse(int result, float xBias, float yBias, float zBias)
        {
            this.result = result;
            this.xBias = xBias;
            this.yBias = yBias;
            this.zBias = zBias;
        }
    }
}
