/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetEndEffectorSuctionCupResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetEndEffectorSuctionCup";

        public int result;
        public byte enableCtrl;
        public byte suck;

        public GetEndEffectorSuctionCupResponse()
        {
            this.result = 0;
            this.enableCtrl = 0;
            this.suck = 0;
        }

        public GetEndEffectorSuctionCupResponse(int result, byte enableCtrl, byte suck)
        {
            this.result = result;
            this.enableCtrl = enableCtrl;
            this.suck = suck;
        }
    }
}
