/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetIOMultiplexingResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetIOMultiplexing";

        public int result;
        public byte multiplex;

        public GetIOMultiplexingResponse()
        {
            this.result = 0;
            this.multiplex = 0;
        }

        public GetIOMultiplexingResponse(int result, byte multiplex)
        {
            this.result = result;
            this.multiplex = multiplex;
        }
    }
}
