/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetIOPWMResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetIOPWM";

        public int result;
        public float frequency;
        public float dutyCycle;

        public GetIOPWMResponse()
        {
            this.result = 0;
            this.frequency = 0.0f;
            this.dutyCycle = 0.0f;
        }

        public GetIOPWMResponse(int result, float frequency, float dutyCycle)
        {
            this.result = result;
            this.frequency = frequency;
            this.dutyCycle = dutyCycle;
        }
    }
}
