/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetIODIResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetIODI";

        public int result;
        public byte level;

        public GetIODIResponse()
        {
            this.result = 0;
            this.level = 0;
        }

        public GetIODIResponse(int result, byte level)
        {
            this.result = result;
            this.level = level;
        }
    }
}
