/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetIOPWMRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetIOPWM";

        public byte address;

        public GetIOPWMRequest()
        {
            this.address = 0;
        }

        public GetIOPWMRequest(byte address)
        {
            this.address = address;
        }
    }
}
