/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetIOADCResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetIOADC";

        public int result;
        public ushort value;

        public GetIOADCResponse()
        {
            this.result = 0;
            this.value = 0;
        }

        public GetIOADCResponse(int result, ushort value)
        {
            this.result = result;
            this.value = value;
        }
    }
}
