/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetJOGCoordinateParamsResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetJOGCoordinateParams";

        public int result;
        public float[] velocity;
        public float[] acceleration;

        public GetJOGCoordinateParamsResponse()
        {
            this.result = 0;
            this.velocity = new float[0];
            this.acceleration = new float[0];
        }

        public GetJOGCoordinateParamsResponse(int result, float[] velocity, float[] acceleration)
        {
            this.result = result;
            this.velocity = velocity;
            this.acceleration = acceleration;
        }
    }
}
