/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetPoseLResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetPoseL";

        public int result;
        public float l;

        public GetPoseLResponse()
        {
            this.result = 0;
            this.l = 0.0f;
        }

        public GetPoseLResponse(int result, float l)
        {
            this.result = result;
            this.l = l;
        }
    }
}
