/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class GetPTPJumpParamsResponse : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/GetPTPJumpParams";

        public int result;
        public float jumpHeight;
        public float zLimit;

        public GetPTPJumpParamsResponse()
        {
            this.result = 0;
            this.jumpHeight = 0.0f;
            this.zLimit = 0.0f;
        }

        public GetPTPJumpParamsResponse(int result, float jumpHeight, float zLimit)
        {
            this.result = result;
            this.jumpHeight = jumpHeight;
            this.zLimit = zLimit;
        }
    }
}
