/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetARCCmdRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetARCCmd";

        public float x1;
        public float y1;
        public float z1;
        public float r1;
        public float x2;
        public float y2;
        public float z2;
        public float r2;

        public SetARCCmdRequest()
        {
            this.x1 = 0.0f;
            this.y1 = 0.0f;
            this.z1 = 0.0f;
            this.r1 = 0.0f;
            this.x2 = 0.0f;
            this.y2 = 0.0f;
            this.z2 = 0.0f;
            this.r2 = 0.0f;
        }

        public SetARCCmdRequest(float x1, float y1, float z1, float r1, float x2, float y2, float z2, float r2)
        {
            this.x1 = x1;
            this.y1 = y1;
            this.z1 = z1;
            this.r1 = r1;
            this.x2 = x2;
            this.y2 = y2;
            this.z2 = z2;
            this.r2 = r2;
        }
    }
}
