/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetARCParamsRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetARCParams";

        public float xyzVelocity;
        public float rVelocity;
        public float xyzAcceleration;
        public float rAcceleration;
        public bool isQueued;

        public SetARCParamsRequest()
        {
            this.xyzVelocity = 0.0f;
            this.rVelocity = 0.0f;
            this.xyzAcceleration = 0.0f;
            this.rAcceleration = 0.0f;
            this.isQueued = false;
        }

        public SetARCParamsRequest(float xyzVelocity, float rVelocity, float xyzAcceleration, float rAcceleration, bool isQueued)
        {
            this.xyzVelocity = xyzVelocity;
            this.rVelocity = rVelocity;
            this.xyzAcceleration = xyzAcceleration;
            this.rAcceleration = rAcceleration;
            this.isQueued = isQueued;
        }
    }
}
