/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetCPParamsRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetCPParams";

        public float planAcc;
        public float junctionVel;
        public float acc;
        public byte realTimeTrack;
        public bool isQueued;

        public SetCPParamsRequest()
        {
            this.planAcc = 0.0f;
            this.junctionVel = 0.0f;
            this.acc = 0.0f;
            this.realTimeTrack = 0;
            this.isQueued = false;
        }

        public SetCPParamsRequest(float planAcc, float junctionVel, float acc, byte realTimeTrack, bool isQueued)
        {
            this.planAcc = planAcc;
            this.junctionVel = junctionVel;
            this.acc = acc;
            this.realTimeTrack = realTimeTrack;
            this.isQueued = isQueued;
        }
    }
}
