/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetDeviceNameRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetDeviceName";

        public String deviceName;

        public SetDeviceNameRequest()
        {
            this.deviceName = new String();
        }

        public SetDeviceNameRequest(String deviceName)
        {
            this.deviceName = deviceName;
        }
    }
}
