/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetEndEffectorGripperRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetEndEffectorGripper";

        public byte enableCtrl;
        public byte grip;
        public bool isQueued;

        public SetEndEffectorGripperRequest()
        {
            this.enableCtrl = 0;
            this.grip = 0;
            this.isQueued = false;
        }

        public SetEndEffectorGripperRequest(byte enableCtrl, byte grip, bool isQueued)
        {
            this.enableCtrl = enableCtrl;
            this.grip = grip;
            this.isQueued = isQueued;
        }
    }
}
