/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetEndEffectorSuctionCupRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetEndEffectorSuctionCup";

        public byte enableCtrl;
        public byte suck;
        public bool isQueued;

        public SetEndEffectorSuctionCupRequest()
        {
            this.enableCtrl = 0;
            this.suck = 0;
            this.isQueued = false;
        }

        public SetEndEffectorSuctionCupRequest(byte enableCtrl, byte suck, bool isQueued)
        {
            this.enableCtrl = enableCtrl;
            this.suck = suck;
            this.isQueued = isQueued;
        }
    }
}
