/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetEMotorSRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetEMotorS";

        public byte index;
        public bool enabled;
        public float speed;
        public float distance;
        public bool isQueued;

        public SetEMotorSRequest()
        {
            this.index = 0;
            this.enabled = false;
            this.speed = 0.0f;
            this.distance = 0.0f;
            this.isQueued = false;
        }

        public SetEMotorSRequest(byte index, bool enabled, float speed, float distance, bool isQueued)
        {
            this.index = index;
            this.enabled = enabled;
            this.speed = speed;
            this.distance = distance;
            this.isQueued = isQueued;
        }
    }
}
