/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetEndEffectorLaserRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetEndEffectorLaser";

        public byte enableCtrl;
        public byte on;
        public bool isQueued;

        public SetEndEffectorLaserRequest()
        {
            this.enableCtrl = 0;
            this.on = 0;
            this.isQueued = false;
        }

        public SetEndEffectorLaserRequest(byte enableCtrl, byte on, bool isQueued)
        {
            this.enableCtrl = enableCtrl;
            this.on = on;
            this.isQueued = isQueued;
        }
    }
}
