/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetIODORequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetIODO";

        public byte address;
        public byte level;
        public bool isQueued;

        public SetIODORequest()
        {
            this.address = 0;
            this.level = 0;
            this.isQueued = false;
        }

        public SetIODORequest(byte address, byte level, bool isQueued)
        {
            this.address = address;
            this.level = level;
            this.isQueued = isQueued;
        }
    }
}
