/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetIOMultiplexingRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetIOMultiplexing";

        public byte address;
        public byte multiplex;
        public bool isQueued;

        public SetIOMultiplexingRequest()
        {
            this.address = 0;
            this.multiplex = 0;
            this.isQueued = false;
        }

        public SetIOMultiplexingRequest(byte address, byte multiplex, bool isQueued)
        {
            this.address = address;
            this.multiplex = multiplex;
            this.isQueued = isQueued;
        }
    }
}
