/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetIOPWMRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetIOPWM";

        public byte address;
        public float frequency;
        public float dutyCycle;
        public bool isQueued;

        public SetIOPWMRequest()
        {
            this.address = 0;
            this.frequency = 0.0f;
            this.dutyCycle = 0.0f;
            this.isQueued = false;
        }

        public SetIOPWMRequest(byte address, float frequency, float dutyCycle, bool isQueued)
        {
            this.address = address;
            this.frequency = frequency;
            this.dutyCycle = dutyCycle;
            this.isQueued = isQueued;
        }
    }
}
