/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetJOGCommonParamsRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetJOGCommonParams";

        public float velocityRatio;
        public float accelerationRatio;
        public bool isQueued;

        public SetJOGCommonParamsRequest()
        {
            this.velocityRatio = 0.0f;
            this.accelerationRatio = 0.0f;
            this.isQueued = false;
        }

        public SetJOGCommonParamsRequest(float velocityRatio, float accelerationRatio, bool isQueued)
        {
            this.velocityRatio = velocityRatio;
            this.accelerationRatio = accelerationRatio;
            this.isQueued = isQueued;
        }
    }
}
