/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetJOGCoordinateParamsRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetJOGCoordinateParams";

        public float[] velocity;
        public float[] acceleration;
        public bool isQueued;

        public SetJOGCoordinateParamsRequest()
        {
            this.velocity = new float[0];
            this.acceleration = new float[0];
            this.isQueued = false;
        }

        public SetJOGCoordinateParamsRequest(float[] velocity, float[] acceleration, bool isQueued)
        {
            this.velocity = velocity;
            this.acceleration = acceleration;
            this.isQueued = isQueued;
        }
    }
}
