/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetJOGCmdRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetJOGCmd";

        public byte isJoint;
        public byte cmd;

        public SetJOGCmdRequest()
        {
            this.isJoint = 0;
            this.cmd = 0;
        }

        public SetJOGCmdRequest(byte isJoint, byte cmd)
        {
            this.isJoint = isJoint;
            this.cmd = cmd;
        }
    }
}
