/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetPTPJumpParamsRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetPTPJumpParams";

        public float jumpHeight;
        public float zLimit;
        public bool isQueued;

        public SetPTPJumpParamsRequest()
        {
            this.jumpHeight = 0.0f;
            this.zLimit = 0.0f;
            this.isQueued = false;
        }

        public SetPTPJumpParamsRequest(float jumpHeight, float zLimit, bool isQueued)
        {
            this.jumpHeight = jumpHeight;
            this.zLimit = zLimit;
            this.isQueued = isQueued;
        }
    }
}
