/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetPTPWithLCmdRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetPTPWithLCmd";

        public byte ptpMode;
        public float x;
        public float y;
        public float z;
        public float r;
        public float l;
        public bool isQueued;

        public SetPTPWithLCmdRequest()
        {
            this.ptpMode = 0;
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.r = 0.0f;
            this.l = 0.0f;
            this.isQueued = false;
        }

        public SetPTPWithLCmdRequest(byte ptpMode, float x, float y, float z, float r, float l, bool isQueued)
        {
            this.ptpMode = ptpMode;
            this.x = x;
            this.y = y;
            this.z = z;
            this.r = r;
            this.l = l;
            this.isQueued = isQueued;
        }
    }
}
