/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetTRIGCmdRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetTRIGCmd";

        public byte address;
        public byte mode;
        public byte condition;
        public ushort threshold;

        public SetTRIGCmdRequest()
        {
            this.address = 0;
            this.mode = 0;
            this.condition = 0;
            this.threshold = 0;
        }

        public SetTRIGCmdRequest(byte address, byte mode, byte condition, ushort threshold)
        {
            this.address = address;
            this.mode = mode;
            this.condition = condition;
            this.threshold = threshold;
        }
    }
}
