/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class SetTransportbeltSpeedRequest : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/SetTransportbeltSpeed";

        public float speed;
        public bool isQueued;

        public SetTransportbeltSpeedRequest()
        {
            this.speed = 0.0f;
            this.isQueued = false;
        }

        public SetTransportbeltSpeedRequest(float speed, bool isQueued)
        {
            this.speed = speed;
            this.isQueued = isQueued;
        }
    }
}
