/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

namespace RosSharp.RosBridgeClient.MessageTypes.Dobot
{
    public class Vector3Request : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "dobot_msgs/Vector3";

        public double xIn;
        public double yIn;
        public double zIn;

        public Vector3Request()
        {
            this.xIn = 0.0;
            this.yIn = 0.0;
            this.zIn = 0.0;
        }

        public Vector3Request(double xIn, double yIn, double zIn)
        {
            this.xIn = xIn;
            this.yIn = yIn;
            this.zIn = zIn;
        }
    }
}
